### PR TITLE
Misc Aesthetic Tweaks by Jonathan

### PR DESCRIPTION
**Pull request by ericboucher**
Got rid of brush font, removed italics, improved consistency/readibility, adjusted line-height, modified font-sizes, fixed typos

### CODE REVIEW

**Comment by mamadOuologuem** [comment]
@bencpeters correct me if I am wrong 
We don't have the `package-lock.json` (create by **npm**) because we are using `yarn.lock` (create by **yarn**)

**Comment by bencpeters** [comment]
> @bencpeters correct me if I am wrong
> We don't have the `package-lock.json` (create by **npm**) because we are using `yarn.lock` (create by **yarn**)

Ya, you're right, I just hadn't looked at this one in a while... Why did the `pacakage-lock.json` get added here then?

**Comment by ericboucher** [comment]
@bencpeters a friend made these tweaks, so that's probably how the npm lock got added. I just removed it.

**Comment by mamadOuologuem** [comment]
localhost_8000_
localhost_8000_ (1)
localhost_8000_ (2)
localhost_8000_ (3)

**Pull request merged**
